version: '3.8'
services:
  api:
    container_name: ms-vecinet-discovery-server
    build: .
    ports:
      - "8761:8761"
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
volumes:
  gradle-cache: